Repository python/peps, pull requests merged in 2018-09, with the labels that each got.

#768 PEP 554: minor corrections.
  pep-0554.rst
Labels: CLA signed

#770 PEP 8002: Add information about Project Jupyter governance
  pep-8002.rst
Labels: CLA signed

#771 PEP 8002: Fix markup
  pep-8002.rst
Labels: CLA signed

#769 PEP-0581: use auto-numbering for footnotes.
  pep-0581.rst
Labels: CLA signed

#744 PEP 484: Clarify definition of AnyStr
  pep-0484.txt
Labels: CLA signed

#772 PEP 8002: Add section describing an idealised version of the process used at Microsoft
  pep-8002.rst
Labels: CLA signed

#777 PEP 8013: The External Council Governance Model
  pep-8013.rst
Labels: CLA signed, governance, in-progress

#778 PEP 8013: Completed first draft
  pep-8013.rst
Labels: CLA signed

#780 PEP 8000: Add reference to PEP 8013
  pep-8000.rst
Labels: CLA signed

#782 PEP 8013: Clarify that a core developer is required to submit PEPs for approval
  pep-8013.rst
Labels: CLA signed

#787 Fix PEP 567 to reflect changes in 3.7.1 (see bpo-34762)
  pep-0567.rst
Labels: CLA signed

#784 PEP 527: Fix typo "Chocalatey" to "Chocolatey"
  pep-0527.txt
Labels: CLA signed

#783 PEP 566: Support for direct references and permit public index servers to add restrictions
  pep-0566.rst
Labels: CLA signed

#781 PEP 580: minor update
  pep-0580.rst
Labels: CLA signed

#789 PEP 1: Add approval criteria to section "Submitting a PEP".
  pep-0001.txt
Labels: CLA signed

#791 (wip) PEP 8011
  pep-8011.rst
Labels: CLA signed, governance

#795 PEP-8013: Add example scenario for BDFL-Delegate role
  pep-8013.rst
Labels: CLA signed, governance

#796 Amend misleading withdrawal notice on PEP 577
  pep-0577.rst
Labels: CLA signed
