Repository python/peps, pull requests merged in 2018-07, with the labels that each got.

#687 PEP 574: add mention of in-band performance
  pep-0574.rst
Labels: CLA signed

#679 PEP 551/578 work
  pep-0551.rst
  pep-0578.rst
Labels: CLA signed

#696 PEP 574: Retitle "Alternatives" to "Rejected alternatives"
  pep-0574.rst
Labels: CLA signed

#693 PEP 505: prepare for 3.8
  pep-0505.txt
Labels: CLA signed, in-progress

#697 Updates to PEP 505
  pep-0505.rst
Labels: CLA signed

#698 Add PEP 572 examples from stdlib
  pep-0572.rst
Labels: CLA signed

#691 Fix trivial typo in pep-0572.rst
  pep-0572.rst
Labels: CLA signed

#688 fix typo
  pep-0562.rst
Labels: CLA not signed

#685 Update PEP 580
  pep-0580.rst
Labels: CLA signed

#664 PEP 8: Fix inconsistent use of line breaks, case and indentation
  pep-0008.txt
Labels: CLA signed

#577 PEP 1: Add a separate "Provisional" PEP status
  pep-0001-1.png
  pep-0001-1.svg
  pep-0001.txt
  pep-0484.txt
  pep-0517.txt
  pep-0518.txt
  pep0/output.py
  pep0/pep.py
Labels: CLA signed

#702 PEP 1: revert to PNG due to SVG rendering issues
  pep-0001.txt
  pep-0001/process_flow.png
  pep-0001/process_flow.svg
Labels: CLA signed

#700 PEP 572: Add Appendix B with translations of various comprehension cases
  pep-0572.rst
Labels: CLA signed

#707 Update PEP-0576 to reflect latest design.
  pep-0576.rst
Labels: CLA signed

#699 Fixes PEP 505 grammar
  pep-0505.rst
Labels: CLA signed

#709 PEP 572: Address several small issues
  pep-0572.rst
Labels: CLA signed

#710 PEP 572: Move the proposed evaluation order change to "Syntax and semantics"
  pep-0572.rst
Labels: CLA signed

#711 PEP 572: Explain why 'as TARGET' is inferior
  pep-0572.rst
Labels: CLA signed

#713 PEP 561: Add link to sample stub packages
  pep-0561.rst
Labels: CLA signed

#712 Add PEPs Contributing Guideline, CoC, and PR template
  .github/PULL_REQUEST_TEMPLATE.md
  CODE_OF_CONDUCT.rst
  CONTRIBUTING.rst
  README.rst
Labels: CLA signed

#715 PEP 572: Fix typo ("assing -> assign")
  pep-0572.rst
Labels: CLA not signed

#716 PEP 572: use double backticks for the ``with`` keyword.
  pep-0572.rst
Labels: CLA signed

#689 PEP 484: Do not require type checkers to treat a None default specially
  pep-0484.txt
Labels: CLA signed

#705 Convert PEP index to ReST
  .gitignore
  Makefile
  genpepindex.py
  pep0/constants.py
  pep0/output.py
  pep0/pep.py
Labels: CLA signed

#717 PEP 572: Delete objection about ugly code
  pep-0572.rst
Labels: CLA signed

#634 Fix pep2rss to specify output encoding
  pep2rss.py
Labels: CLA signed

#720 PEP 572: disallow ungrouped assign-expr in annotations
  pep-0572.rst
Labels: CLA signed

#725 PEP 572 occurrs -> occurs typo
  pep-0572.rst
Labels: CLA not signed

#718 PEP 572: Tweaks suggested by Glenn Linterman
  pep-0572.rst
Labels: CLA signed

#726 Linkify the PEP numbers in "Superseded-By" header.
  pep-0101.txt
  pep-0292.txt
  pep-0435.txt
  pep-0446.txt
  pep-3156.txt
  pep2html.py
  pep2pyramid.py
Labels: CLA signed

#727 Update .travis.yml, build using Python 3.7-dev instead of 3.5
  .travis.yml
Labels: CLA signed

#724 PEP 572: Annotations are supported, via separate declarations
  pep-0572.rst
Labels: CLA signed

#719 PEP 572: Assorted fixes suggested by Rob Cliffe
  pep-0572.rst
Labels: CLA signed

#730 PEP 572: Remove extra curly brace from dict display example
  pep-0572.rst
Labels: CLA signed

#732 PEP 572: clarify Appendix C example
  pep-0572.rst
Labels: CLA signed

#733 PEP 572: pass mandatory bufsize sock.recv() argument
  pep-0572.rst
Labels: CLA signed

#729 PEP 572: Add another UAEAP bullet point
  pep-0572.rst
Labels: CLA signed

#734 PEP 572: Fix extra "than" typo
  pep-0572.rst
Labels: CLA signed

#736 PEP 505: Improve examples and refer to other relevant PEPs
  pep-0505.rst
Labels: CLA signed

#735 PEP 572: Acceptance
  pep-0572.rst
Labels: CLA signed

#739 PEP 572: Mention the two minor changes in the Abstract
  pep-0572.rst
Labels: CLA signed

#738 Update the PR template and Contributing Guidelines
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.rst
Labels: CLA signed

#741 PEP 580: minor update
  pep-0580.rst
Labels: CLA signed

#745 PEP 306: Fix dead links for Dev Guide and BPO issue
  pep-0306.txt
Labels: CLA signed

#747 PEP 505 updates
  pep-0505.rst
  pep-0505/find-pep505.py
Labels: CLA signed

#749 PEP 580: minor update
  pep-0580.rst
Labels: CLA signed

#750 PEP 574: mention experimental support in Apache Arrow
  pep-0574.rst
Labels: CLA signed
