Repository python/peps, pull requests merged in 2019-04, with the labels that each got.

#964 PEP 0508: change identifer_end rule to identifier_end
  pep-0508.txt
Labels: CLA signed

#967 PEP 580: new flag CCALL_DEFARG instead of CCALL_FUNCARG
  pep-0580.rst
Labels: CLA signed

#968 PEP 578: Rename open_for_import to io.open_code
  pep-0578.rst
Labels: CLA signed, in-progress

#969 PEP 533: Make Guido BDFL-Delegate
  pep-0533.txt
Labels: CLA signed

#963 PEP 570: Add a 'How to teach this' section and improve rejected ideas section with feedback from discourse
  pep-0570.rst
Labels: CLA signed

#970 PEP 533: Correction: Make Yury BDFL-Delegate
  pep-0533.txt
Labels: CLA signed

#960 PEP 590: A new calling convention for CPython
  pep-0590.rst
Labels: CLA signed

#972 PEP 570: Restructure sections as recommended by PEP 1
  pep-0570.rst
Labels: CLA signed

#974 PEP 544: Fix typo in code block
  pep-0544.txt
Labels: CLA not signed

#975 PEP 570: Edit Sections and How to Teach
  pep-0570.rst
Labels: CLA signed

#977 PEP 570: Accept
  pep-0570.rst
Labels: CLA signed

#978 PEP 570: Demonstrate a corner case
  pep-0570.rst
Labels: CLA signed

#966 PEP 440: regex should not permit Unicode [Nd] characters
  pep-0440.txt
Labels: CLA signed

#949 PEP 534: Improve title and clarify proposal
  pep-0534.txt
Labels: CLA signed

#973 PEP 590: minor edits
  pep-0590.rst
Labels: CLA signed

#979 PEP 336: Change semicolons to colons at function definitions
  pep-0336.txt
Labels: CLA signed

#982 Package all pep files. Fixes python/pythondotorg#1394
  Makefile
Labels: CLA signed

#980 PEP 590: Clarify the use of PY_VECTORCALL_ARGUMENTS_OFFSET.
  pep-0590.rst
Labels: CLA signed

#856 PEP 517: Improve wording on including setup.py in the source distribution
  pep-0517.txt
Labels: CLA signed

#985 PEP 578: Add clarifications around open_code() for non-code files
  pep-0578.rst
Labels: CLA signed

#986 PEP 578: Add Post History
  pep-0578.rst
Labels: CLA signed

#987 PEP 554: Return a boolean from send_nowait() rather than raising an exception.
  pep-0554.rst
Labels: CLA signed

#981 PEP 581: Minor text edits
  pep-0581.rst
Labels: CLA signed

#858 PEP 484: Add @type_check_only
  pep-0484.txt
Labels: CLA signed

#990 PEP 591: Adding a final qualifier to typing
  pep-0591.rst
Labels: CLA signed

#984 PEP 590: Add "Vectorcall" and "fastcall" keywords
  pep-0590.rst
Labels: CLA signed

#991 PEP 589: Minor typo/grammar/wording/markup fixes
  pep-0589.rst
Labels: CLA signed

#994 PEP 591: some minor cleanups
  pep-0591.rst
Labels: CLA signed

#993 PEP 586: Small wording changes from review; expanded example in Abstract
  pep-0586.rst
Labels: CLA signed

#965 PEP 432: Update based on the extracted PEP 587 API
  pep-0432.txt
  pep-0587.rst
Labels: CLA signed

#996 PEP 586: Add section about Final
  pep-0586.rst
Labels: CLA signed

#999 PEP 586: typo (MAy -> May)
  pep-0586.rst
Labels: CLA not signed

#995 PEP 586: Make backwards compatibility best-effort
  pep-0586.rst
Labels: CLA signed

#1001 PEP 586, PEP 589, PEP 591: Make Guido BDFL-Delegate of typing PEPs
  pep-0586.rst
  pep-0589.rst
  pep-0591.rst
Labels: CLA signed

#1002 Make myself BD for PEP 387 on behalf of the SC
  pep-0387.txt
Labels: CLA signed

#1003 Make Brett Cannon the BD for PEP 487 on behalf of the steering council
  pep-0497.txt
Labels: CLA signed

#997 PEP 586: Rewrite sections regarding enum
  pep-0586.rst
Labels: CLA signed

#1006 PEP 573: Defer to Python 3.9
  pep-0573.rst
Labels: CLA signed

#1005 PEP 467: Defer, and update open questions
  pep-0467.txt
Labels: CLA signed

#1007 PEP 557: Data Classes - Mark as Final
  pep-0557.rst
Labels: CLA signed

#1008 PEP 558: Appoint BDFL-Delegate and other updates
  pep-0558.rst
Labels: CLA signed

#992 PEP 590: Remove unnecessary PyObject_VectorCall function.
  pep-0590.rst
Labels: CLA signed

#1011 PEP 573: Stefan Behnel has accepted the BDFL-Delegate role
  pep-0573.rst
Labels: CLA signed

#1015 PEP 554: Change target version to 3.9.
  pep-0554.rst
Labels: CLA signed

#1016 PEP 554: Defer adding support for "inheriting" settings.
  pep-0554.rst
Labels: CLA signed

#1017 PEP 574: Final updates
  pep-0574.rst
Labels: CLA signed

#1013 PEP 581, 588: Split GitHub migration rationale and plan into two separate PEPs
  pep-0581.rst
  pep-0588.rst
Labels: CLA signed
