Repository python/peps, pull requests merged in 2019-10, with the labels that each got.

#1186 Pep 0604 : Change title
  pep-0604.rst
Labels: CLA signed

#1187 PEP 587: PyConfig_InitPythonConfig() cannot fail anymore
  pep-0587.rst
Labels: CLA signed

#1180 PEP 571: Update GCC_4.5.0
  pep-0571.rst
Labels: CLA signed

#1184 PEP 605: A rolling feature release stream for CPython
  pep-0598.rst
  pep-0605.rst
Labels: CLA signed

#1188 PEP 605: Update initial publication info
  pep-0605.rst
Labels: CLA signed

#1193 PEP 487: Remove extra underscore.
  pep-0487.txt
Labels: CLA signed, bug

#1192 PEP 604: Make Ivan BDFL-Delegate
  pep-0604.rst
Labels: CLA signed

#1190 PEP 605: Change ABI management to encourage pre-built wheels
  pep-0605-example-release-calendar.png
  pep-0605-overlapping-support-matrix.png
  pep-0605.rst
  pep-0605/example-release-calendar.odp
  pep-0605/overlapping-support-matrix.odp
Labels: CLA signed

#1196 PEP 605: Add 2nd post date
  pep-0605.rst
Labels: CLA signed

#1200 PEP 605: Add example user-facing docs
  pep-0605.rst
Labels: CLA signed

#1195 PEP 440: Normalize date version examples
  pep-0440.txt
Labels: CLA signed

#1191 PEP 600: Small updates in response to Paul's feedback
  pep-0600.rst
Labels: CLA signed

#962 PEP 503: Reword to match pip’s URL lookup behavior
  pep-0503.txt
Labels: CLA signed

#1206 PEP 584: Remove subtraction and add more background.
  pep-0584.rst
Labels: CLA signed, enhancement

#1209 Add PEP 606: Python Compatibility Version
  pep-0606.rst
Labels: CLA signed

#1208 PEP 008: Fix in Pet Peeves example for consistency
  pep-0008.txt
Labels: CLA signed

#1211 PEP 607: Shared background for release cadence change proposals
  pep-0607.rst
Labels: CLA signed

#1213 PEP 607: Update Discussions-To header
  pep-0607.rst
Labels: CLA signed

#1214 PEP 584: Fix formatting and update copyright notice.
  pep-0584.rst
Labels: CLA signed

#1210 PEP 0571: compiler version matching x86_64 docker image
  pep-0571.rst
Labels: CLA signed

#1215 Assign a BDFL-Delegate for PEP 602
  pep-0602.rst
Labels: CLA signed

#1197 PEP 13: Change the Council Election to use Approval voting.
  pep-0013.rst
Labels: CLA signed

#1216 PEP 345: Improve example for the Project-URL field and clarify purpose
  pep-0345.txt
Labels: CLA signed

#1059 PEP 541: Add section on how to request a name transfer
  pep-0541.txt
Labels: CLA signed

#1217 PEP 517: fix typos
  pep-0517.txt
Labels: CLA signed
