Repository python/peps, pull requests merged in 2020-05, with the labels that each got.

#1389 PEP: Add Optional Length-Checking To zip
  pep-0618.rst
Labels: CLA signed, enhancement

#1390 PEP 554: updates based on feedback
  pep-0554.rst
Labels: CLA signed

#1391 Reject PEP 349: Outdated by Python 3
  pep-0349.txt
Labels: CLA signed

#1395 PEP 581/588: Discussions to: core-workflow on Discourse
  pep-0581.rst
  pep-0588.rst
Labels: CLA signed

#1394 PEP 554: push the target release back.
  pep-0554.rst
Labels: CLA signed

#1399 PEP 618: Second Draft
  pep-0618.rst
Labels: CLA signed

#1401 PEP 617: Fix citation for Medeiros ([2])
  pep-0617.rst
Labels: CLA signed

#1404 PEP 431: Mention PEP 615
  pep-0431.txt
Labels: CLA signed

#1371 Make `from __future__ import annotations` the default in Python 3.10
  pep-0563.rst
Labels: CLA signed

#1406 PEP 563: Make `from __future__ import annotations` the default in Python 3.10
  pep-0563.rst
Labels: CLA signed

#1408 PEP 615: Add back missing example output
  pep-0615.rst
Labels: CLA signed

#1409 Specify pep-0584 order guarantee
  pep-0584.rst
Labels: CLA signed

#1411 PEP 318: Replace dead link with Internet Archive version
  pep-0318.txt
Labels: CLA signed

#1413 PEP 484: Add missing single quote to sample code
  pep-0484.txt
Labels: CLA not signed

#1415 PEP 619: Fix creation date
  pep-0619.rst
Labels: CLA signed

#1414 PEP 619: fix year for 3.10.0 final
  pep-0619.rst
Labels: CLA signed

#1416 PEP 619: Fix version number and date of beta 1
  pep-0619.rst
Labels: CLA signed

#1418 PEP 617: Fix typos
  pep-0617.rst
Labels: CLA signed

#1417 PEP 596: Add the list of PEPs implemented in Python 3.9.0b1
  pep-0596.rst
Labels: CLA signed
