Repository python/peps, pull requests merged in 2020-03, with the labels that each got.

#1323 PEP 615: Changes to TZPATH and str, plus minor tweaks
  pep-0615.rst
Labels: CLA signed

#1324 Clarify that the CDATA for a repo index should match the project name not the normalized name
  pep-0503.txt
Labels: CLA signed

#1326 PEP 458: Fix figure reference and typo
  pep-0458.txt
Labels: CLA signed

#1327 PEP 534: Mark as Deferred
  pep-0534.txt
Labels: CLA signed

#1329 PEP 458: correct spelling of 'infrastucture'
  pep-0458.txt
Labels: CLA not signed

#1330 PEP 610: Provisional Acceptance
  pep-0610.rst
Labels: CLA signed

#1328 PEP 499: Mark as deferred until 3.10
  pep-0499.txt
Labels: CLA signed

#1331 PEP 584: Add info regarding Mapping/MutableMapping
  pep-0584.rst
Labels: CLA signed, enhancement

#1332 PEP 616: String methods to remove prefixes and suffixes
  pep-0616.rst
Labels: CLA signed

#1333 PEP 616 Revisions
  pep-0616.rst
Labels: CLA signed

#1335 PEP 616: Add references to past discussion threads, fix formatting and typos
  pep-0616.rst
Labels: CLA signed

#1338 PEP 3154: fix typo
  pep-3154.txt
Labels: CLA signed

#1336 PEP 616: Fix behavior of code snippets
  pep-0616.rst
Labels: CLA signed

#1340 PEP 616: Rename the methods and restrict to one affix
  pep-0616.rst
Labels: CLA signed

#1343 PEP 616: Remove obsolete names; consistently quote strings
  pep-0616.rst
Labels: CLA signed

#1344 PEP 616: Make the specification more concise
  pep-0616.rst
Labels: CLA signed

#1345 PEP 483: Remove reference to implicitly Optional parameters
  pep-0483.txt
Labels: CLA signed

#1346 PEP 616: Add revision history
  pep-0616.rst
Labels: CLA signed

#1348 PEP 487: typo fix
  pep-0487.txt
Labels: CLA signed

#1347 PEP 615: Resolve "using datetime" and add rationale to updates section
  pep-0615.rst
Labels: CLA signed

#1351 PEP 617: New PEG parser for CPython
  pep-0617.rst
Labels: CLA signed
