Repository python/peps, pull requests merged in 2022-08, with the labels that each got.

#2744 Infra: Fix docutils deprecation warning when generating RSS
  generate_rss.py
  requirements.txt
Labels: infra

#2702 Infra: Add new directives to point to PEP's canonical content
  conf.py
  pep-0012.rst
  pep_sphinx_extensions/__init__.py
  pep_sphinx_extensions/pep_processor/parsing/pep_banner_directive.py
Labels: enhancement, infra

#2715 PEP 501: Fix footnotes
  pep-0501.txt
Labels: bug

#2741 PEP 565: Fix footnotes
  pep-0565.rst
Labels: bug

#2762 PEP 678: fix typo in sample code
  pep-0678.rst
Labels: bug

#2751 PEP 550: Fix footnotes
  pep-0550.rst
Labels: bug

#2752 PEP 467: Fix footnotes
  pep-0467.txt
Labels: bug

#2754 PEP 558: fix footnote references
  pep-0558.rst
Labels: bug

#2756 Lint: Update outdated Python-Version on still-Draft PEPs
  pep-0467.txt
  pep-0554.rst
  pep-0558.rst
  pep-0603.rst
  pep-0619.rst
  pep-0620.rst
  pep-0664.rst
  pep-0671.rst
  pep-0674.rst
  pep-0679.rst
  pep-0684.rst
  pep-0689.rst
Labels: lint

#2757 Lint: Add missing Python-Version header in PEPs
  pep-0229.txt
  pep-0305.txt
  pep-0307.txt
  pep-0308.txt
  pep-0311.txt
  pep-0341.txt
  pep-0352.txt
  pep-0353.txt
  pep-0397.txt
  pep-0409.txt
  pep-0414.txt
  pep-0421.txt
  pep-0436.txt
  pep-0441.txt
  pep-0443.txt
  pep-0476.txt
  pep-0523.txt
  pep-3106.txt
  pep-3119.txt
  pep-3138.txt
  pep-3141.txt
  pep-3156.txt
Labels: lint

#2740 Infra: Mute table zebra stripes to de-emphasise different rows
  pep_sphinx_extensions/pep_theme/static/style.css
Labels: infra

#2772 PEP 697 (new): C-API for Extending Opaque Types
  .github/CODEOWNERS
  pep-0697.rst
Labels: new-pep
