Repository python/peps, pull requests merged in 2022-04, with the labels that each got.

#2496 PEP 686: Add schedule for each spec.
  pep-0686.rst
Labels: CLA signed

#2498 PEP 681: Decorator placement, future params, unstated semantics
  pep-0681.rst
Labels: CLA signed

#2475 Infra: generate machine-readable PEP index
  pep_sphinx_extensions/pep_zero_generator/parser.py
  pep_sphinx_extensions/pep_zero_generator/pep_index_generator.py
Labels: CLA signed, infra

#2494 Fix colour scheme toggling when switching from default dark mode
  pep_sphinx_extensions/pep_theme/static/colour_scheme.js
Labels: bug, CLA signed, infra

#2499 PEP 687: Isolating modules in the standard library
  pep-0687.rst
Labels: CLA signed

#2501 PEP 687: Add Discussions-To & Post-History
  pep-0687.rst
Labels: CLA signed

#2503 PEP 681: Rename "field descriptor" to "field specifier"
  pep-0681.rst
Labels: CLA signed

#2504 PEP 681: Add kwargs on dataclass_transform
  pep-0681.rst
Labels: CLA signed

#2378 Meta: Clearly document current guidance for changing existing PEPs
  CONTRIBUTING.rst
  pep-0001.txt
Labels: CLA signed, meta

#2510 PEP 664: 3.11.0 alpha 7 released
  pep-0664.rst
Labels: CLA not signed

#2509 Infra: Restore PEPs RSS feed in <head>
  pep_sphinx_extensions/pep_theme/templates/page.html
Labels: bug, CLA signed, infra

#2482 PEP 671: Add Discussions-To header
  pep-0671.rst
Labels: CLA signed

#2506 PEP 631: Update status to clarify incorperation into PEP 621
  pep-0631.rst
Labels: CLA signed

#2507 PEP 681: Fix header links
  pep-0681.rst
Labels: CLA signed, lint

#2485 Build Instructions: Fix to work with the latest Makefile
  docs/build.rst
Labels: CLA signed, meta

#2534 PEP 595: replace mismatched references with inline links
  pep-0595.rst
Labels: bug

#2442 PEP 11: define tiered platform support
  pep-0011.txt
Labels: CLA signed

#2533 Style: Reduce space consumed by headers and improve alignment
  pep_sphinx_extensions/pep_processor/transforms/pep_title.py
  pep_sphinx_extensions/pep_theme/static/style.css
Labels: infra

#2467 Infra: Improve email and link processing and rendering in headers
  pep-0009.txt
  pep_sphinx_extensions/pep_processor/transforms/pep_headers.py
Labels: CLA signed, infra

#2532 Infra: remove two of the five instances of title at top of pages
  pep_sphinx_extensions/pep_theme/static/style.css
  pep_sphinx_extensions/pep_theme/templates/page.html
Labels: infra

#2459 PEP 630: Format and copyedit prior to conversion into a docs HOWTO guide
  pep-0630.rst
Labels: CLA signed

#2541 Style: Retitle inline 'Contents' to 'Table of Contents' for clarity
  pep_sphinx_extensions/pep_processor/html/pep_html_translator.py
Labels: infra

#2542 Lint: Optimize images to reduce file size by 1.5-2x for free
  pep-0001-process_flow.png
  pep-0001.txt
  pep-0458-1.png
  pep-0480-1.png
  pep-0495-daylightsavings.png
  pep-0495-fold-2.png
  pep-0495-gap.png
  pep-0495.txt
  pep-0525-1.png
  pep-0602-example-release-calendar.png
  pep-0602-overlapping-support-matrix.png
  pep-0605-example-release-calendar.png
  pep-0605-overlapping-support-matrix.png
  pep-3147-1.png
Labels: lint

#2551 Infra: Add note on finding the RTD preview
  README.rst
Labels: meta

#2549 PEP 688: Making the buffer protocol accessible in Python
  .github/CODEOWNERS
  pep-0688.rst
Labels: new-pep

#1711 PEP 480: Clarify automated signing solution to remove key sharing
  pep-0480.txt
Labels: CLA signed

#2545 Infra: add tests
  .github/workflows/render.yml
  .github/workflows/test.yml
  .gitignore
  .pre-commit-config.yaml
  Makefile
  pep_sphinx_extensions/pep_processor/transforms/pep_headers.py
  pep_sphinx_extensions/pep_zero_generator/author.py
  pep_sphinx_extensions/tests/__init__.py
  pep_sphinx_extensions/tests/pep_processor/transform/test_pep_footer.py
  pep_sphinx_extensions/tests/pep_processor/transform/test_pep_headers.py
  pep_sphinx_extensions/tests/pep_processor/transform/test_pep_zero.py
  pep_sphinx_extensions/tests/pep_zero_generator/test_author.py
  pep_sphinx_extensions/tests/pep_zero_generator/test_parser.py
  pep_sphinx_extensions/tests/pep_zero_generator/test_pep_index_generator.py
  pep_sphinx_extensions/tests/pep_zero_generator/test_writer.py
  pep_sphinx_extensions/tests/peps/pep-9000.rst
  pep_sphinx_extensions/tests/peps/pep-9001.rst
  pep_sphinx_extensions/tests/utils.py
  pytest.ini
  requirements.txt
  tox.ini
Labels: infra

#2552 Infra: Make the color scheme toggle into a three-state cycler
  pep_sphinx_extensions/pep_theme/static/colour_scheme.js
  pep_sphinx_extensions/pep_theme/static/colour_scheme.svg
  pep_sphinx_extensions/pep_theme/static/dark.css
  pep_sphinx_extensions/pep_theme/static/style.css
  pep_sphinx_extensions/pep_theme/templates/page.html
  pep_sphinx_extensions/pep_theme/templates/partials/icons.html
Labels: infra

#2368 PEP 638: Typographic fixes
  pep-0638.rst
Labels: CLA signed
