Repository python/peps, pull requests merged in 2022-09, with the labels that each got.

#2791 PEP 532, 577, 598: Fix footnotes references
  pep-0532.txt
  pep-0577.rst
  pep-0598.rst
Labels: bug

#2794 PEP 366, 395, 413, 426, 430, 440, 531, 535, 3150: Fix footnotes
  pep-0366.txt
  pep-0395.txt
  pep-0413.txt
  pep-0426.txt
  pep-0430.txt
  pep-0440.txt
  pep-0531.txt
  pep-0535.txt
  pep-3150.txt
Labels: bug

#2775 PEP 1: Update main PEP discussion venue from Python-Dev to Discourse
  pep-0001.txt
Labels: meta

#2783 PEP 698: Override Decorator for Static Typing (`@typing.override`)
  .github/CODEOWNERS
  pep-0698.rst
Labels: new-pep
