Repository python/peps, pull requests merged in 2022-01, with the labels that each got.

#2210 PEP 646: Fix code markup
  pep-0646.rst
Labels: CLA signed

#2211 Various PEPs: fix typos
  pep-0011.txt
  pep-0498.txt
  pep-0558.rst
  pep-0639.rst
  pep-0665.rst
  pep-0674.rst
  pep-0676.rst
  pep-0677.rst
  pep-3104.txt
Labels: CLA signed

#2213 Delete CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: CLA signed

#2214 PEP 11: Ungender the volunteer pronoun.
  pep-0011.txt
Labels: CLA signed

#2216 PEP 677: Use PEP 646 syntax when discussing unpack
  pep-0677.rst
Labels: CLA signed

#2207 PEP 676: Formatting and prose updates
  pep-0676.rst
Labels: CLA signed

#2208 PEP 676: Implementation updates
  .github/workflows/deploy-gh-pages.yaml
  Makefile
  build.py
  conf.py
  generate_rss.py
  pep-0456.txt
  pep_sphinx_extensions/__init__.py
  pep_sphinx_extensions/config.py
  pep_sphinx_extensions/pep_processor/html/pep_html_builder.py
  pep_sphinx_extensions/pep_processor/html/pep_html_translator.py
  pep_sphinx_extensions/pep_processor/parsing/pep_role.py
  pep_sphinx_extensions/pep_processor/transforms/pep_footer.py
  pep_sphinx_extensions/pep_processor/transforms/pep_headers.py
  pep_sphinx_extensions/pep_processor/transforms/pep_zero.py
  pep_sphinx_extensions/pep_theme/static/doctools.js
  pep_sphinx_extensions/pep_theme/static/style.css
  pep_sphinx_extensions/pep_theme/templates/page.html
  pep_sphinx_extensions/pep_zero_generator/writer.py
Labels: CLA signed

#2220 PEP 679: Allow parentheses in assert statements
  pep-0679.rst
Labels: CLA signed

#2221 PEP 679: Change the discussions link
  pep-0679.rst
Labels: CLA signed

#2222 Copyedits to PEP 679
  .github/CODEOWNERS
  pep-0679.rst
Labels: CLA signed

#2218 PEP 680: "tomllib" Support for parsing TOML in the Standard Library
  pep-0680.rst
Labels: CLA signed

#2223 PEP 680: Address merwok's review
  pep-0680.rst
Labels: CLA signed

#2219 PEP 677: Include more rejected alternatives
  pep-0677.rst
Labels: CLA signed

#2224 PEP 677: Add Discussions-To and Post-History headers
  pep-0677.rst
Labels: CLA signed

#2225 PEP 677: Minor wording and formatting fixes.
  pep-0677.rst
Labels: CLA signed

#2227 Set low priority for rm-ing refs section so refs still resolve correctly
  pep2html.py
Labels: CLA signed

#2229 Fix refs section removal breaking external links on Sphinx build too
  pep_sphinx_extensions/pep_processor/transforms/pep_footer.py
Labels: CLA signed

#2226 PEP 680: link discuss post, minor edits
  .github/CODEOWNERS
  pep-0680.rst
Labels: CLA signed

#2230 PEP 677: Format the flat_map example consistently
  pep-0677.rst
Labels: CLA signed

#2231 PEP 673: Mention user requests for the feature.
  pep-0673.rst
Labels: CLA signed

#2232 PEP 673: Add Post-History.
  pep-0673.rst
Labels: CLA signed

#2154 PEP 613: Loosen class scope restriction of explicit TypeAlias
  pep-0613.rst
Labels: CLA signed

#2236 PEP 677: fix typo in example
  pep-0677.rst
Labels: CLA signed

#2235 PEP 648: Update status to rejected
  pep-0648.rst
Labels: CLA signed

#2241 PEP 646: Clarify indexing assignment
  pep-0646.rst
Labels: CLA signed

#2240 PEP 458: update references to python-tuf repo
  pep-0458.txt
Labels: CLA signed

#2242 PEP 673: minor fixes to the code samples
  pep-0673.rst
Labels: CLA signed

#2239 PEP 676: 'dark mode', documentation, spec update, implementation update
  Makefile
  build.py
  conf.py
  contents.rst
  docs/build.rst
  docs/rendering_system.rst
  generate_rss.py
  pep-0009.txt
  pep-0011.txt
  pep-0610.rst
  pep-0625.rst
  pep-0676.rst
  pep-3139.txt
  pep_sphinx_extensions/LICENCE.rst
  pep_sphinx_extensions/__init__.py
  pep_sphinx_extensions/pep_processor/html/pep_html_builder.py
  pep_sphinx_extensions/pep_processor/transforms/pep_footer.py
  pep_sphinx_extensions/pep_theme/static/colour_scheme.js
  pep_sphinx_extensions/pep_theme/static/colour_scheme.svg
  pep_sphinx_extensions/pep_theme/static/dark.css
  pep_sphinx_extensions/pep_theme/static/style.css
  pep_sphinx_extensions/pep_theme/templates/page.html
  pep_sphinx_extensions/pep_theme/theme.conf
Labels: CLA signed

#2245 Fix Sphinx build
  conf.py
Labels: CLA signed

#2244 PEP 8: update example of backslash usage for with statements
  pep-0008.txt
Labels: CLA signed

#2246 PEP 669: Return current callback object when registering a new callback.
  pep-0669.rst
Labels: CLA signed

#2243 Fix function signatures in PEP 677
  pep-0677.rst
Labels: CLA signed

#2247 PEP 674: Relationship with the HPy project
  pep-0674.rst
Labels: CLA signed

#2237 PEP 677: Runtime Behavior Specification
  pep-0677.rst
Labels: CLA signed

#2249 PEP 674: Address Tim Felgentreff's review
  pep-0674.rst
Labels: CLA signed

#2250 PEP 646: Mark as Accepted
  pep-0646.rst
Labels: CLA signed

#2251 Allow title and fragments in PEP and RFC references
  pep2html.py
Labels: CLA signed

#2253 Add Adam Turner as the default reviewer for PEP infrastructure
  .github/CODEOWNERS
Labels: CLA signed

#2254 Fix missing quotes around python-dev in overrides causing display bug
  AUTHOR_OVERRIDES.csv
Labels: bug, CLA signed

#2215 Allow manually running GitHub Actions workflows and use consistent file extension
  .github/workflows/build.yml
  .github/workflows/deploy-gh-pages.yml
  .github/workflows/lint.yml
Labels: CLA signed

#2228 PEP 639: Update PEP delegate, post history and CODEOWNERS
  .github/CODEOWNERS
  pep-0639.rst
Labels: CLA signed

#2248 PEP 655: Integrate feedback from circa Feb 2021
  pep-0655.rst
Labels: CLA signed

#2256 PEP 1: Update language on PEP-Delegate field
  pep-0001.txt
Labels: CLA signed

#1996 Only restrict to deploying on pushes to `master` in the python/peps repo
  .github/workflows/deploy-gh-pages.yml
Labels: CLA signed

#2258 Remove needless gender specific terms. #855
  pep-0311.txt
  pep-0355.txt
  pep-0381.txt
  pep-0458.txt
  pep-3119.txt
  pep-3127.txt
Labels: CLA signed

#2257 PEP 1: Further refine phrasing and organization of PEP-Delegate description
  pep-0001.txt
Labels: CLA signed

#2259 PEP 1: Use plain text formatting and fix links
  pep-0001.txt
Labels: CLA signed

#2260 PEP 676: Mention additional enhacements
  .github/CODEOWNERS
  pep-0676.rst
Labels: CLA signed

#2261 PEP 646: Add acceptance note, bump Python version
  pep-0646.rst
Labels: CLA signed

#2151 Add configuration for running `codespell` locally
  .codespell/exclude-file.txt
  .codespell/ignore-words.txt
  .codespellrc
  .pre-commit-config.yaml
  Makefile
Labels: CLA signed

#2264 Exclude `.codespell` from Sphinx
  conf.py
Labels: CLA signed

#2269 PEP 673: Mark as Accepted and add Resolution link
  pep-0673.rst
Labels: CLA signed

#2267 PEP 13 and PEP 245: Fix incorrect PEP references
  pep-0013.rst
  pep-0245.txt
Labels: CLA signed

#2271 PEP 0008: Replaced outdated usages of `print` as a statement
  pep-0008.txt
Labels: CLA not signed

#2272 PEP 13: Update 2022 Steering Council per PEP 8103 results
  pep-0013.rst
Labels: CLA signed

#2263 PEP 7: Clarify that compiler extensions are prohibited in general, not just GCC
  pep-0007.txt
Labels: CLA signed

#2262 PEP 594: add myself as co-author and target for Python 3.11
  .github/CODEOWNERS
  pep-0594.rst
Labels: CLA signed

#2274 PEP 594: remove modules from the list that are already gone or deprecated
  pep-0594.rst
Labels: CLA signed

#2275 PEP 676: Barry Warsaw is the delegate
  pep-0676.rst
Labels: CLA signed

#2205 PEP 678: more rejected ideas
  pep-0678.rst
Labels: CLA signed

#2277 PEP 674: Leave PyDescr_TYPE() unchanged
  pep-0674.rst
Labels: CLA signed

#2280 PEP 674: only 9 projects are affected
  pep-0674.rst
Labels: CLA signed

#2279 PEP 675: Clarify wording in various sections
  pep-0675.rst
Labels: CLA signed

#2283 PEP 678: Update link to documentation PR
  pep-0678.rst
Labels: CLA signed

#2281 PEP 680: Further explain why files are read as binary
  pep-0680.rst
Labels: CLA signed

#2278 PEP 680: Note that double precision float is a recommendation not requirement
  pep-0680.rst
Labels: CLA signed

#2284 PEP 674: List fixed projects; change title
  pep-0674.rst
Labels: CLA signed

#2287 PEP 655: Integrate feedback circa Jan 2022
  pep-0655.rst
Labels: CLA signed

#2288 Fail on Docutils warning
  pep_sphinx_extensions/__init__.py
Labels: CLA signed

#2285 PEP 681: Data Class Transforms
  .github/CODEOWNERS
  pep-0681.rst
Labels: CLA signed
