Repository python/peps, pull requests merged in 2022-11, with the labels that each got.

#2863 PEP 383: Fix broken link
  pep-0383.txt
Labels: bug

#2826 Meta: Clarify scope of Packaging topic and rm ensurepip PEPs (453/477)
  pep-0453.txt
  pep-0477.txt
  pep_sphinx_extensions/pep_zero_generator/constants.py
Labels: meta

#2879 Infra: Include PEP number in API
  pep_sphinx_extensions/pep_zero_generator/parser.py
Labels: infra

#2875 PEP 8104: 2023 Term Steering Council election
  pep-0013.rst
  pep-8104.rst
Labels: new-pep

#2900 Meta: Update Contrib Guide & PR template for new CLA bot
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.rst
Labels: meta

#2842 Infra: Link status and type headers to descriptions
  pep_sphinx_extensions/pep_processor/transforms/pep_headers.py
  pep_sphinx_extensions/pep_zero_generator/constants.py
  pep_sphinx_extensions/pep_zero_generator/parser.py
  pep_sphinx_extensions/pep_zero_generator/writer.py
  pep_sphinx_extensions/tests/pep_processor/transform/test_pep_headers.py
  pep_sphinx_extensions/tests/pep_zero_generator/test_parser.py
Labels: infra
