Repository python/peps, pull requests merged in 2022-03, with the labels that each got.

#2372 PEP 683: Immortal Objects v3
  pep-0683.rst
Labels: CLA signed

#2377 PEP 678: Clarify how the notes tuple is updated and when it is copied
  pep-0678.rst
Labels: CLA signed

#2374 PEP 12: Update spacing/breaking conventions to match current practice
  pep-0012.rst
  pep-0012/pep-NNNN.rst
Labels: CLA signed

#2380 PEP 484: Update status from Provisional to Final
  pep-0484.txt
Labels: CLA signed

#2379 Lint: Implement check for spaces, not tabs per PEP 12
  .pre-commit-config.yaml
  pep-8100.rst
  pep-8101.rst
  pep-8102.rst
  pep-8103.rst
Labels: CLA signed, lint

#2383 PEP 682: Updating headers for PEP acceptance
  pep-0682.rst
Labels: CLA signed

#2381 PEP 681: kw_only field descriptor parameter is supported
  pep-0681.rst
Labels: CLA signed

#2386 PEP 681: Remove discussion of alternate form
  pep-0681.rst
Labels: CLA signed

#2382 PEP 681: Fix minor formatting and typographical issues
  pep-0681.rst
Labels: CLA signed

#2389 PEP 664: Update actual 3.11a6 release date
  pep-0664.rst
Labels: CLA signed

#2391 PEP 685: Comparison of extra names for optional distribution dependencies
  .github/CODEOWNERS
  pep-0685.rst
Labels: CLA signed

#2392 Meta: fix CODEOWNERS
  .github/CODEOWNERS
Labels: CLA signed

#2390 PEP 681: Describe CPython changes and include docs link
  pep-0681.rst
Labels: CLA signed

#2387 PEP 684: Add a PEP for making the GIL per-interpreter
  .github/CODEOWNERS
  pep-0684.rst
Labels: CLA signed

#2394 PEP 683: Drop Eddie from CODEOWNERS
  .github/CODEOWNERS
Labels: CLA signed

#2393 PEP 684: Update Discussions-To and Post-History
  pep-0684.rst
Labels: CLA signed

#2397 PEP 619: Remove duplicated expected release date
  pep-0619.rst
Labels: CLA not signed

#2358 PEP 1 & 12: Have Post-History link posts to preserve Discussions-To history
  pep-0001.txt
  pep-0012.rst
  pep-0012/pep-NNNN.rst
Labels: CLA signed

#2395 PEP 684: Fix invalid format for Discussions-To header
  pep-0684.rst
Labels: bug, CLA signed

#2396 PEP 685: Conform to PEP 12, address textual errors and improve clarity and phrasing
  pep-0685.rst
Labels: CLA signed

#2398 legally dropped the middle name and suffix.
  AUTHOR_OVERRIDES.csv
  pep-0458.txt
  pep-0588.rst
  pep-8001.rst
  pep-8100.rst
  pep-8101.rst
  pep-8102.rst
  pep-8103.rst
Labels: CLA signed

#2401 PEP 0: Fix 'Page Source (GitHub)'
  pep_sphinx_extensions/pep_theme/templates/page.html
Labels: CLA signed

#2399 The PEP Rendering System is dead; long live the PEP Rendering System
  .github/CODEOWNERS
  .github/workflows/build.yml
  .github/workflows/render.yml
  CONTRIBUTING.rst
  Makefile
  PyRSS2Gen.py
  README.rst
  deploy.bash
  docs/build.rst
  docutils.conf
  generate_rss.py
  genpepindex.py
  pep-0001.txt
  pep-0009.txt
  pep-0287.txt
  pep-0465/scan-ops.py
  pep-0676.rst
  pep-8001.rst
  pep.css
  pep0/__init__.py
  pep0/constants.py
  pep0/output.py
  pep0/pep.py
  pep2html.py
  pep2rss.py
  pep_sphinx_extensions/__init__.py
  pyramid-pep-template
  roman.py
  style.css
Labels: CLA signed

#2411 PEP 685: address review feedback
  pep-0685.rst
Labels: CLA signed

#2410 Infra: Upload rendered PEPs as GitHub artifact
  .github/workflows/lint.yml
  .github/workflows/render.yml
Labels: CLA signed, infra

#2023 PRS: Enable PR previews
  build.py
  pep_sphinx_extensions/__init__.py
  readthedocs.yaml
Labels: CLA signed

#2409 Dark mode: invert some images
  pep-0001.txt
  pep-0458.txt
  pep-0480.txt
  pep-0495.txt
  pep-0525.txt
  pep-0532.txt
  pep-0550.rst
  pep-0603.rst
  pep-3147.txt
  pep_sphinx_extensions/pep_theme/static/dark.css
Labels: CLA signed, infra

#2414 PEP 594: Mark as accepted
  pep-0594.rst
Labels: CLA signed

#2416 PEP 594: Set Resolution header
  pep-0594.rst
Labels: CLA signed

#2417 PRS: Remove artifact upload
  .github/workflows/render.yml
Labels: CLA signed

#2418 PEP 685: address review comments
  pep-0685.rst
Labels: CLA signed

#2412 PEP 659: Link to final version of Brunthaler paper
  pep-0659.rst
Labels: CLA signed

#2419 PEP 673: Fix a couple of typos
  pep-0673.rst
Labels: CLA signed

#2413 PRS: Fix RSS generation and resolve all warnings
  generate_rss.py
Labels: CLA signed

#2408 Lint: call tools inside venv using make's PYTHON
  Makefile
Labels: CLA signed, lint

#2422 PEP 440: note that setuptools comparison is historical
  pep-0440.txt
Labels: CLA signed

#2385 Meta: Classify Accepted Process PEPs as non-historical & mark PEP 8001 Final
  pep-8001.rst
  pep_sphinx_extensions/pep_zero_generator/writer.py
Labels: CLA signed, meta

#2415 PRS: Explicitly list files to render
  conf.py
  pep_sphinx_extensions/__init__.py
Labels: CLA signed

#2425 Styling: Remove field block highlights and restore definition list indent
  pep_sphinx_extensions/pep_theme/static/style.css
Labels: CLA signed

#2364 Make the table of contents collapsed by default
  pep-0249.txt
  pep-0512.txt
  pep_sphinx_extensions/pep_processor/html/pep_html_builder.py
  pep_sphinx_extensions/pep_processor/html/pep_html_translator.py
  pep_sphinx_extensions/pep_processor/transforms/pep_contents.py
  pep_sphinx_extensions/pep_theme/static/style.css
Labels: CLA signed

#2431 PEP 339: Fix broken link
  pep-0339.txt
Labels: CLA signed

#2369 PEP 681: Descriptor fields
  pep-0681.rst
Labels: CLA signed

#2426 Accessibility: Add aria-label to clearly describe the dark mode button
  pep_sphinx_extensions/pep_theme/templates/page.html
Labels: CLA signed, infra

#2433 PEP 594: Fix minor typo
  pep-0594.rst
Labels: CLA signed

#2432 PEP 20: Fix syntax highlighting and other minor syntax/formatting issues
  pep-0020.txt
Labels: bug, CLA signed

#2434 PEP 594: minor fix of hyperlinks in table of replacements
  pep-0594.rst
Labels: CLA not signed

#2435 PEP 673: Fix syntax highlighting
  pep-0673.rst
Labels: CLA signed

#2436 PEP 537, 569, 596: Update bugfix release date
  pep-0537.txt
  pep-0569.rst
  pep-0596.rst
Labels: CLA signed

#2428 PEP 685: Copyedit and fix various minor issues following further changes
  pep-0685.rst
Labels: CLA signed

#2427 Style: Fix vertical margins of def lists w/o <p>s to match those with
  pep_sphinx_extensions/pep_theme/static/style.css
Labels: CLA signed, infra

#2438 PEP 589: Fix typo - index 'y' needs quotes
  pep-0589.rst
Labels: CLA signed

#2440 PEP 594: Fix typo: deprecate nis in 3.11 not 3.8
  pep-0594.rst
Labels: CLA signed

#2443 PEP 686: Make UTF-8 mode default
  pep-0686.rst
Labels: CLA signed

#2289 PEP 668: Keep the marker file in container images
  pep-0668.rst
Labels: CLA signed

#2444 PEP 686: Update URLs, PEP references, Discussions-To and CODEOWNERS per PEP 12
  .github/CODEOWNERS
  pep-0686.rst
Labels: CLA signed

#2450 PEP 630: Add sections for 2 more gotchas
  pep-0630.rst
Labels: CLA signed

#2452 PEP 675: Mark as accepted
  pep-0675.rst
Labels: CLA signed

#2448 PEP 685: Minor wording changes
  pep-0685.rst
Labels: CLA signed

#2446 PEP 686: Update based on discussion
  pep-0686.rst
Labels: CLA signed

#2458 PEP 659: Reformat to obey 80 column limit
  pep-0659.rst
Labels: CLA signed

#2451 PEP 655: Mark as accepted
  pep-0655.rst
Labels: CLA signed

#2439 Style: Reduce size of code font and improve responsiveness at narrow screen widths
  pep_sphinx_extensions/pep_theme/static/mq.css
  pep_sphinx_extensions/pep_theme/static/style.css
  pep_sphinx_extensions/pep_theme/static/wrap_tables.js
  pep_sphinx_extensions/pep_theme/templates/page.html
Labels: bug, CLA signed, infra

#2454 PEP 681: Remove hash alias for unsafe_hash
  pep-0681.rst
Labels: CLA signed

#2457 PEP 686: Change target version to 3.13
  pep-0686.rst
Labels: CLA signed

#2445 PEP 1, 12: Update to reflect guidance for correct syntax highlighting
  pep-0001.txt
  pep-0012.rst
Labels: CLA signed, lint, meta

#2456 PEP 678: simplify specification to use a list
  pep-0678.rst
Labels: CLA signed

#2466 PEP 619: Add 3.10.4 release
  pep-0619.rst
Labels: CLA signed

#2465 PEP 596: Add 3.9.12 release
  pep-0596.rst
Labels: CLA signed

#2447 PEP 1, 12: Update for adoption of PEP 676, and fix a few related items
  .pre-commit-config.yaml
  README.rst
  contents.rst
  pep-0001.txt
  pep-0012.rst
  pep-0685.rst
Labels: CLA signed, infra, lint, meta

#2463 Style: Scroll code blocks instead of wrapping them
  pep_sphinx_extensions/pep_theme/static/style.css
Labels: CLA signed, infra

#2429 PEP 0: Make PEP titles in table clickable links
  pep_sphinx_extensions/pep_processor/transforms/pep_zero.py
Labels: CLA signed, infra

#2464 PEP 686: Grammar fixes
  pep-0686.rst
Labels: CLA signed

#2462 PEP 659: Update to describe inline caches
  pep-0659.rst
Labels: CLA signed

#2472 Update pep-0665.rst much to must
  pep-0665.rst
Labels: CLA not signed

#2473 PEP 3138: add missing backslash
  pep-3138.txt
Labels: CLA signed

#2474 Infra: Include trailing slash in RSS URLs to avoid 301 redirect
  Makefile
  generate_rss.py
Labels: CLA signed, infra

#2461 PEP 670: Rearrange and reword the PEP
  pep-0670.rst
Labels: CLA signed

#2480 PEP 396: Fix `importlib.metadata.version` reference
  pep-0396.txt
Labels: CLA signed

#2481 PEP 570: Mark as Final
  pep-0570.rst
Labels: CLA signed

#2488 PEP 681: Rejected Ideas cleanup
  pep-0681.rst
Labels: CLA signed

#2470 PEP 686: Update
  pep-0686.rst
Labels: CLA signed

#2478 Style: Fix unbounded max width causing very wide spans to overflow
  pep_sphinx_extensions/pep_theme/static/mq.css
Labels: bug, CLA signed, infra

#2489 PEP 686: Update Post-History
  pep-0686.rst
Labels: CLA signed

#2477 PEP 681: Move descriptor-field support to Rejected Ideas
  pep-0681.rst
Labels: CLA signed

#2490 PEP 686: Update Discussions-To to match Post-History
  pep-0686.rst
Labels: CLA signed
