Repository python/peps, pull requests merged in 2022-07, with the labels that each got.

#2096 PEP 453: only remove setuptools once pip drops support for legacy installs
  pep-0453.txt
Labels: CLA signed

#2697 PEP 695: Type Parameter Syntax
  .github/CODEOWNERS
  pep-0695.rst
Labels: new-pep

#2698 PEP 661: Fix citation references
  pep-0661.rst
Labels: bug

#2691 Style: Fix colors and style for all admonitions
  pep_sphinx_extensions/pep_theme/static/style.css
Labels: enhancement, infra

#2687 Infra: Fix canonical link tag to point to correct PEP URL
  pep_sphinx_extensions/pep_theme/static/colour_scheme.js
  pep_sphinx_extensions/pep_theme/static/style.css
  pep_sphinx_extensions/pep_theme/templates/page.html
Labels: bug, infra

#2683 Infra: gitignore generated `/topic` and wipe via `make clean`
  .gitignore
  Makefile
Labels: infra

#2718 PEP 642: Fix footnotes
  pep-0642.rst
Labels: bug

#2714 PEP 538: Fix footnotes
  pep-0538.txt
Labels: bug

#2729 PEP 432: fix code block
  pep-0432.txt
Labels: bug

#2736 PEP 601: Fix footnotes
  pep-0601.txt
Labels: bug

#2735 PEP 634: Fix duplicate labels
  pep-0634.rst
Labels: bug

#2742 PEP 635: fix duplicate labels
  pep-0635.rst
Labels: bug

#2743 PEP 605: fix footnotes
  pep-0605.rst
Labels: bug

#2728 Infra: override RTD build commands
  .github/workflows/render.yml
  Makefile
  build.py
  readthedocs.yaml
Labels: infra

#2727 Infra: Test Python 3.11 beta
  .github/workflows/lint.yml
  .github/workflows/render.yml
  .github/workflows/test.yml
  .gitignore
  pytest.ini
Labels: infra
