Repository python/peps, pull requests merged in 2022-06, with the labels that each got.

#2616 Infra: Use Docutils' `list-table` syntax for PEP 0
  pep_sphinx_extensions/pep_processor/transforms/pep_zero.py
  pep_sphinx_extensions/pep_theme/static/style.css
  pep_sphinx_extensions/pep_zero_generator/parser.py
  pep_sphinx_extensions/pep_zero_generator/writer.py
  pep_sphinx_extensions/tests/pep_zero_generator/test_parser.py
Labels: infra

#2638 PEP 484: Fix citation references
  pep-0484.txt
Labels: bug

#2649 PEP 619, 664: Fix release date in comment
  pep-0619.rst
  pep-0664.rst
Labels: bug

#2644 PEP 554: Fix citation references
  pep-0554.rst
Labels: bug

#2579 Add support for topic indices
  .pre-commit-config.yaml
  contents.rst
  pep_sphinx_extensions/pep_processor/html/pep_html_builder.py
  pep_sphinx_extensions/pep_zero_generator/constants.py
  pep_sphinx_extensions/pep_zero_generator/parser.py
  pep_sphinx_extensions/pep_zero_generator/pep_index_generator.py
  pep_sphinx_extensions/pep_zero_generator/subindices.py
  pep_sphinx_extensions/pep_zero_generator/writer.py
  pep_sphinx_extensions/tests/pep_zero_generator/test_parser.py
  pep_sphinx_extensions/tests/pep_zero_generator/test_pep_index_generator.py
  pep_sphinx_extensions/tests/pep_zero_generator/test_writer.py
Labels: infra

#2648 PEP 693: Python 3.12 Release Schedule
  pep-0693.rst
Labels: new-pep

#2639 PEP 553: Fix citation references
  pep-0553.rst
Labels: bug

#2640 PEP 593: Fix citation references
  pep-0593.rst
Labels: bug

#2619 Infra: Make colour theme cycler button accessible
  pep_sphinx_extensions/pep_theme/static/style.css
  pep_sphinx_extensions/pep_theme/templates/page.html
Labels: infra

#2675 PEP 694: Upload 2.0 API for Python Package Repositories
  pep-0694.rst
Labels: new-pep

#2620 PEP 692: Using TypedDict for more precise `**kwargs` typing
  .github/CODEOWNERS
  pep-0692.rst
Labels: new-pep

#2689 Infra: Link topic index pages in rendered PEP topic headers
  pep_sphinx_extensions/pep_processor/transforms/pep_headers.py
Labels: enhancement, infra

#2678 Remove the requirement for Resolution to be the final header
  .pre-commit-config.yaml
Labels: lint
