Repository python/peps, pull requests merged in 2022-10, with the labels that each got.

#2805 Style: Fix zebra stripes and improve table & code presentation
  pep_sphinx_extensions/pep_theme/static/style.css
Labels: infra

#2810 Remove ``include_patterns`` monkeypatching
  conf.py
  pep_sphinx_extensions/__init__.py
  requirements.txt
Labels: infra

#2816 Infra + many PEPs: Add Sphinx Lint and fix errors
  .pre-commit-config.yaml
  pep-0372.txt
  pep-0453.txt
  pep-0462.txt
  pep-0481.txt
  pep-0507.txt
  pep-0534.txt
  pep-0555.rst
  pep-0633.rst
  pep-0639.rst
  pep-0653.rst
  pep-0692.rst
  pep_sphinx_extensions/LICENCE.rst
Labels: bug, infra

#2823 Topic pages: remove authors table
  pep_sphinx_extensions/pep_zero_generator/writer.py
Labels: infra

#2670 Add Typing Topic
  pep-0482.txt
  pep-0483.txt
  pep-0484.txt
  pep-0526.txt
  pep-0544.txt
  pep-0563.rst
  pep-0585.rst
  pep-0586.rst
  pep-0589.rst
  pep-0591.rst
  pep-0593.rst
  pep-0604.rst
  pep-0612.rst
  pep-0613.rst
  pep-0646.rst
  pep-0647.rst
  pep-0649.rst
  pep-0655.rst
  pep-0673.rst
  pep-0675.rst
  pep-0677.rst
  pep-0681.rst
  pep-0688.rst
  pep-0692.rst
  pep-0695.rst
  pep-0698.rst
  pep_sphinx_extensions/pep_zero_generator/constants.py
Labels: enhancement, meta

#2690 Packaging PEPs: Update headers & link canonical PyPA specs
  pep-0241.txt
  pep-0262.txt
  pep-0314.txt
  pep-0345.txt
  pep-0376.txt
  pep-0425.txt
  pep-0427.txt
  pep-0566.rst
  pep-0610.rst
  pep-0621.rst
  pep-0627.rst
  pep-0643.rst
  pep-0685.rst
  pep_sphinx_extensions/pep_processor/parsing/pep_banner_directive.py
Labels: lint

#2825 Lint: Upgrade linters, enable backtick check & fix new errors
  .pre-commit-config.yaml
  pep-0240.txt
  pep-0357.txt
  pep-0447.txt
  pep-0461.txt
Labels: lint

#2835 Lint: Add a new check for consistent PEP header order
  .pre-commit-config.yaml
  pep-0440.txt
  pep-0441.txt
  pep-0523.txt
  pep-0612.rst
Labels: lint

#2840 PEP 700: Additional Fields for the Simple API for Package Indexes
  .github/CODEOWNERS
  pep-0700.rst
Labels: new-pep

#2838 Infra: Add tooltips to type/status in PEP 0
  pep_sphinx_extensions/pep_processor/html/pep_html_translator.py
  pep_sphinx_extensions/pep_theme/static/style.css
  pep_sphinx_extensions/pep_zero_generator/parser.py
  pep_sphinx_extensions/pep_zero_generator/subindices.py
  pep_sphinx_extensions/pep_zero_generator/writer.py
  pep_sphinx_extensions/tests/pep_zero_generator/test_parser.py
Labels: infra

#2841 Infra: Declare Makefile targets as phony
  Makefile
Labels: bug, infra

#2839 Infra: Only emit a category table when it has entries
  pep_sphinx_extensions/pep_zero_generator/writer.py
Labels: infra

#2843 Infra: Don't generate broken source link for topic pages
  pep_sphinx_extensions/pep_theme/templates/page.html
Labels: bug, infra

#2858 Infra: Add 'make help'
  Makefile
Labels: infra
