Repository python/peps, pull requests merged in 2023-09, with the labels that each got.

#3295 Infra: Have PEP 0 index by the name in the PEP
  AUTHOR_OVERRIDES.csv
  pep_sphinx_extensions/pep_zero_generator/author.py
  pep_sphinx_extensions/pep_zero_generator/parser.py
  pep_sphinx_extensions/pep_zero_generator/writer.py
  pep_sphinx_extensions/tests/pep_zero_generator/test_author.py
  pep_sphinx_extensions/tests/pep_zero_generator/test_parser.py
  pep_sphinx_extensions/tests/pep_zero_generator/test_writer.py
  pep_sphinx_extensions/tests/utils.py
Labels: infra

#3339 PEP 0: Set consistent table column widths
  pep_sphinx_extensions/pep_theme/static/style.css
Labels: infra

#3415 Lint: Enable pre-commit default role checks
  .pre-commit-config.yaml
Labels: lint

#3417 Infra: Prepare for moving PEPs to a subfolder
  .github/CODEOWNERS
  conf.py
  pep_sphinx_extensions/pep_processor/parsing/pep_banner_directive.py
  pep_sphinx_extensions/pep_processor/transforms/pep_footer.py
  pep_sphinx_extensions/pep_theme/templates/page.html
  pep_sphinx_extensions/pep_zero_generator/pep_index_generator.py
  pep_sphinx_extensions/pep_zero_generator/subindices.py
  pep_sphinx_extensions/pep_zero_generator/writer.py
  pep_sphinx_extensions/tests/conftest.py
  pep_sphinx_extensions/tests/pep_processor/transform/test_pep_footer.py
  pep_sphinx_extensions/tests/pep_zero_generator/test_parser.py
  pep_sphinx_extensions/tests/pep_zero_generator/test_pep_index_generator.py
Labels: infra

#3420 Update documentation and build.py
  build.py
  docs/build.rst
  docs/rendering_system.rst
Labels: infra

#3275 Lint: Add ``check-peps.py``
  .github/CODEOWNERS
  .github/workflows/lint.yml
  .pre-commit-config.yaml
  check-peps.py
  pep_sphinx_extensions/generate_rss.py
  pep_sphinx_extensions/tests/conftest.py
  pep_sphinx_extensions/tests/pep_lint/__init__.py
  pep_sphinx_extensions/tests/pep_lint/test_date.py
  pep_sphinx_extensions/tests/pep_lint/test_direct_links.py
  pep_sphinx_extensions/tests/pep_lint/test_email.py
  pep_sphinx_extensions/tests/pep_lint/test_headers.py
  pep_sphinx_extensions/tests/pep_lint/test_pep_lint.py
  pep_sphinx_extensions/tests/pep_lint/test_pep_number.py
  pep_sphinx_extensions/tests/pep_lint/test_post_url.py
  pep_sphinx_extensions/tests/peps/pep-9002.rst
  pytest.ini
Labels: DO-NOT-MERGE, lint

#3422 Infra: Use actions/checkout version 4
  .github/workflows/lint.yml
  .github/workflows/render.yml
  .github/workflows/test.yml
Labels: infra

#3433 Lint: Update Ruff config
  .github/workflows/lint.yml
  .pre-commit-config.yaml
Labels: lint

#3266 PEP 724: Stricter TypeGuard
  .github/CODEOWNERS
  peps/pep-0724.rst
Labels: new-pep

#3453 PEP 1: Cease recommending Typing-SIG (it has ceased to be!)
  CONTRIBUTING.rst
  peps/pep-0001.rst
Labels: meta

#3434 Infra: Add Python version to PEP 0 tables
  pep_sphinx_extensions/pep_theme/static/style.css
  pep_sphinx_extensions/pep_zero_generator/parser.py
  pep_sphinx_extensions/pep_zero_generator/writer.py
  pep_sphinx_extensions/tests/pep_zero_generator/test_parser.py
Labels: infra
