Repository python/peps, pull requests merged in 2023-07, with the labels that each got.

#3195 Infra: Call sphinx-build directly in Makefile instead of via build.py wrapper
  Makefile
  conf.py
Labels: infra

#3188 PEP 715: Fix link to packaging term
  pep-0715.rst
Labels: bug

#3192 PEP 720: add "Cross-compiling Python packages" PEP draft
  .github/CODEOWNERS
  pep-0720.rst
Labels: new-pep

#3189 PEP 554: Convert unreferenced footnote to bullet point
  pep-0554.rst
Labels: bug

#3218 Infra: Revert "Fix a URL in the PyPA specification banner (#3199)"
  pep_sphinx_extensions/pep_processor/parsing/pep_banner_directive.py
Labels: infra

#3225 PEP 326: Remore unreferenced footnotes and renumber
  pep-0326.txt
Labels: bug, lint
