Repository python/peps, pull requests merged in 2023-01, with the labels that each got.

#2942 PEP 702: Type system support for deprecations
  .github/CODEOWNERS
  pep-0702.rst
Labels: new-pep

#2949 Infra: Only invert image brightness, not hue
  pep_sphinx_extensions/pep_theme/static/style.css
Labels: infra

#2952 Uncap the Sphinx requirement
  requirements.txt
Labels: infra

#2962 Infra: link directly to RSS feed at peps.python.org
  pep_sphinx_extensions/pep_theme/templates/page.html
Labels: infra

#2968 Infra: Use consistent 'make html' and 'make dirhtml'
  .github/workflows/render.yml
  Makefile
  readthedocs.yaml
Labels: infra

#2973 Infra: replace feedgen/lxml dependency to test Python 3.12-dev
  .github/workflows/render.yml
  .github/workflows/test.yml
  Makefile
  generate_rss.py
  readthedocs.yaml
  requirements.txt
  tox.ini
Labels: infra

#2972 Infra: Use relative links to ease development
  pep_sphinx_extensions/__init__.py
  pep_sphinx_extensions/pep_processor/parsing/pep_role.py
  pep_sphinx_extensions/pep_processor/transforms/pep_headers.py
Labels: infra

#2965 PEP 495: Fix incorrect gap image
  pep-0495-gap.svg
Labels: bug

#2981 Infra: Fix Replaces/Superseded-By/Requires links for dirhtml
  pep_sphinx_extensions/pep_processor/transforms/pep_headers.py
Labels: bug, infra

#2977 Infra: Use dark grey instead of dark green for dark theme background
  pep_sphinx_extensions/pep_theme/static/style.css
Labels: infra

#2964 PEP 704: Require virtual environments by default for installers
  .github/CODEOWNERS
  pep-0704.rst
Labels: new-pep

#2994 Infra: Update precommit to fix Poetry
  .pre-commit-config.yaml
Labels: lint
