Repository python/peps, pull requests merged in 2024-04, with the labels that each got.

#3751 PEP 744: JIT Compilation
  .github/CODEOWNERS
  peps/pep-0744.rst
Labels: new-pep

#3682 Infra: Add directives to show warning banner for deprecated PEPs
  pep_sphinx_extensions/__init__.py
  pep_sphinx_extensions/pep_processor/parsing/pep_banner_directive.py
  peps/pep-0003.rst
  peps/pep-0009.rst
  peps/pep-0042.rst
  peps/pep-0103.rst
  peps/pep-0204.rst
  peps/pep-0206.rst
  peps/pep-0209.rst
  peps/pep-0210.rst
  peps/pep-0211.rst
  peps/pep-0215.rst
  peps/pep-0216.rst
  peps/pep-0220.rst
  peps/pep-0224.rst
  peps/pep-0225.rst
  peps/pep-0239.rst
  peps/pep-0241.rst
  peps/pep-0242.rst
  peps/pep-0363.rst
  peps/pep-0426.rst
Labels: enhancement, infra

#3758 Infra: Skip Sphinx 7.3 to fix missing 404s
  requirements.txt
Labels: infra

#3760 Infra: Fix 404s
  pep_sphinx_extensions/__init__.py
  requirements.txt
Labels: infra

#3764 PEP 745: Python 3.14 release schedule
  .github/CODEOWNERS
  peps/pep-0745.rst
Labels: new-pep
