Repository python/peps, pull requests merged in 2024-10, with the labels that each got.

#4008 PEP 758: Allow ``except`` and ``except*`` expressions without parentheses
  .github/CODEOWNERS
  peps/pep-0758.rst
Labels: new-pep

#4021 Infra: Mention 'Superseded' in section heading
  pep_sphinx_extensions/pep_zero_generator/writer.py
Labels: infra

#4027 PEP 761: Deprecating PGP signatures for CPython artifacts
  .github/CODEOWNERS
  peps/pep-0761.rst
Labels: new-pep

#4044 Pin Sphinx to <8.1
  requirements.txt
Labels: infra

#4045 PEP 0: Use an absolute link to `peps.json`
  pep_sphinx_extensions/pep_zero_generator/writer.py
Labels: infra

#4048 PEP 762: REPL-acing the default REPL
  .github/CODEOWNERS
  peps/pep-0762.rst
Labels: new-pep

#4033 Infra: update header to 'Process and Meta-PEPs'
  pep_sphinx_extensions/pep_zero_generator/writer.py
Labels: infra

#4071 Meta: Run check-peps.py in pre-commit
  .github/workflows/lint.yml
  .pre-commit-config.yaml
Labels: meta

#4077 PEP 8106: 2025 Term Steering Council election
  peps/pep-8106.rst
Labels: new-pep
